name: Saeedthon_Run
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Saeedthon
        env:
          INSTA_USER: ${{ secrets.INSTA_USER }}
          INSTA_PASS: ${{ secrets.INSTA_PASS }}
          WA_NUMBER: ${{ secrets.WA_NUMBER }}
          WA_SESSION: ${{ secrets.WA_SESSION }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
        run: python Saeedthon.py
