name: Saeedthon_24_7

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-saeedthon:
    runs-on: ubuntu-latest
    
    concurrency:
      group: saeedthon-group
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # تم التحديث لنسخة 3.10 لتعمل المكاتب بدون مشاكل
          python-version: '3.10'

      - name: Install Essential Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Dependencies
        run: |
          # تثبيت المكاتب الأساسية قبل تشغيل السكريبت
          python -m pip install --upgrade pip
          pip install telethon instagrapi neonize-bin Flask gunicorn heroku3 requests
          # إذا كان ملف requirements.txt موجوداً، سيثبت البقية
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Saeedthon
        env:
          INSTA_USER: ${{ secrets.INSTA_USER }}
          INSTA_PASS: ${{ secrets.INSTA_PASS }}
          WA_NUMBER: ${{ secrets.WA_NUMBER }}
          WA_SESSION: ${{ secrets.WA_SESSION }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
        run: |
          python Saeedthon.py
        
    timeout-minutes: 350
